name: Python CI/DE with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: CD with SSH
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Upload project code
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          target: /home/ubuntu/python_ml/python_source
          source: .
          
      # EC2에 SSH로 배포 커맨드를 입력하는 step
      - name: Deploy SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          # 기존 실행 중인 서버 종료 후 jar 파일 실행
          script: |
            sudo fuser -k -n tcp 5000
            sleep 15
            sudo python server.py
          # 위에 sudo nohup ~~~ 대신에 파이썬 실행 커맨드 명령어 입력. 로깅안해도 되는데 해주면 내가 디버깅할 때 도움 엄청많이될 예정